# Generated by Django 5.2.15 on 2026-07-04 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('commons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='货位编码')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='货位名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '货位',
                'verbose_name_plural': '货位',
                'db_table': 'inventory_location',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='仓库编码')),
                ('name', models.CharField(max_length=200, verbose_name='仓库名称')),
                ('address', models.TextField(blank=True, verbose_name='地址')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '仓库',
                'verbose_name_plural': '仓库',
                'db_table': 'inventory_warehouse',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='商品编码')),
                ('name', models.CharField(max_length=200, verbose_name='商品名称')),
                ('spec', models.CharField(blank=True, max_length=500, verbose_name='规格型号')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='商品分类')),
                ('purchase_price',
                 models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='采购价')),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='销售价')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='税率(%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+',
                                   to=settings.AUTH_USER_MODEL)),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commons.uom',
                                          verbose_name='基本计量单位')),
                ('updated_by',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+',
                                   to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 'inventory_product',
            },
        ),
        migrations.CreateModel(
            name='StockMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_type',
                 models.CharField(choices=[('IN', '入库'), ('OUT', '出库')], max_length=10, verbose_name='移动类型')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='移动数量')),
                ('unit_price',
                 models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='移动单价')),
                ('reference_type', models.CharField(max_length=50, verbose_name='来源单据类型')),
                ('reference_id', models.BigIntegerField(verbose_name='来源单据ID')),
                ('reference_line_id', models.BigIntegerField(blank=True, null=True, verbose_name='来源单据行ID')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL,
                                   verbose_name='操作人')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                               to='inventory.location', verbose_name='货位')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product',
                                              verbose_name='商品')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse',
                                                verbose_name='仓库')),
            ],
            options={
                'verbose_name': '库存移动流水',
                'verbose_name_plural': '库存移动流水',
                'db_table': 'inventory_stock_move',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity',
                 models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='当前库存量')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                               to='inventory.location', verbose_name='货位')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product',
                                              verbose_name='商品')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse',
                                                verbose_name='仓库')),
            ],
            options={
                'verbose_name': '库存',
                'verbose_name_plural': '库存',
                'db_table': 'inventory_stock',
            },
        ),
        migrations.AddField(
            model_name='location',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations',
                                    to='inventory.warehouse', verbose_name='所属仓库'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['code'], name='inventory_p_code_a06c9c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='inventory_p_categor_b457a1_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmove',
            index=models.Index(fields=['product', 'warehouse'], name='inventory_s_product_42cd97_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmove',
            index=models.Index(fields=['move_type'], name='inventory_s_move_ty_adf7e0_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmove',
            index=models.Index(fields=['created_at'], name='inventory_s_created_c57995_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmove',
            index=models.Index(fields=['reference_type', 'reference_id'], name='inventory_s_referen_cce129_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['product', 'warehouse'], name='inventory_s_product_112b63_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('product', 'warehouse', 'location')},
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('warehouse', 'code')},
        ),
    ]
