# Generated by Django 5.2.15 on 2026-07-04 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.CharField(max_length=50, unique=True, verbose_name='凭证号')),
                ('voucher_type', models.CharField(
                    choices=[('purchase_in', '采购入库'), ('sales_out', '销售出库'), ('stock_adjust', '库存调整')],
                    max_length=20, verbose_name='凭证类型')),
                ('order_no', models.CharField(blank=True, max_length=50, verbose_name='来源单号')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='金额')),
                ('voucher_date', models.DateField(auto_now_add=True, verbose_name='凭证日期')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL,
                                   verbose_name='制单人')),
                ('stock_move', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                 to='inventory.stockmove', verbose_name='关联库存移动')),
            ],
            options={
                'verbose_name': '会计凭证',
                'verbose_name_plural': '会计凭证',
                'db_table': 'finance_voucher',
            },
        ),
        migrations.CreateModel(
            name='VoucherLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_code', models.CharField(max_length=20, verbose_name='科目编码')),
                ('account_name', models.CharField(max_length=100, verbose_name='科目名称')),
                ('direction',
                 models.CharField(choices=[('debit', '借方'), ('credit', '贷方')], max_length=10, verbose_name='方向')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='金额')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines',
                                              to='finance.voucher', verbose_name='凭证')),
            ],
            options={
                'verbose_name': '凭证分录行',
                'verbose_name_plural': '凭证分录行',
                'db_table': 'finance_voucherline',
            },
        ),
    ]
