# Generated by Django 5.2.15 on 2026-07-04 09:30

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='单位名称')),
                ('short_name', models.CharField(max_length=10, verbose_name='简称')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='单位类别')),
            ],
            options={
                'verbose_name': '计量单位',
                'verbose_name_plural': '计量单位',
                'db_table': 'commons_uom',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False,
                                                     help_text='Designates that this user has all permissions without explicitly assigning them.',
                                                     verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'},
                                              help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.',
                                              max_length=150, unique=True,
                                              validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                                              verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False,
                                                 help_text='Designates whether the user can log into this admin site.',
                                                 verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True,
                                                  help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.',
                                                  verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='手机号')),
                ('employee_id',
                 models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='工号')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='部门')),
                ('avatar', models.URLField(blank=True, verbose_name='头像')),
                ('is_online', models.BooleanField(default=False, verbose_name='在线状态')),
                ('groups', models.ManyToManyField(blank=True,
                                                  help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
                                                  related_name='user_set', related_query_name='user', to='auth.group',
                                                  verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.',
                                                            related_name='user_set', related_query_name='user',
                                                            to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'users_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='编码')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('type', models.CharField(
                    choices=[('customer', '客户'), ('supplier', '供应商'), ('both', '既是客户又是供应商')],
                    max_length=20, verbose_name='类型')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='电话')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('address', models.TextField(blank=True, verbose_name='地址')),
                ('credit_limit',
                 models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='信用额度')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+',
                                   to=settings.AUTH_USER_MODEL)),
                ('updated_by',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+',
                                   to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '合作伙伴',
                'verbose_name_plural': '合作伙伴',
                'db_table': 'commons_partner',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='角色名称')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='角色编码')),
                ('description', models.TextField(blank=True, verbose_name='角色描述')),
                ('is_system', models.BooleanField(default=False, verbose_name='系统角色')),
                ('permissions', models.ManyToManyField(blank=True, to='auth.permission', verbose_name='权限')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'db_table': 'commons_role',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, to='commons.role', verbose_name='角色'),
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=10, verbose_name='前缀')),
                ('year', models.IntegerField(verbose_name='年')),
                ('month', models.IntegerField(verbose_name='月')),
                ('day', models.IntegerField(verbose_name='日')),
                ('last_number', models.IntegerField(default=0, verbose_name='最后号码')),
            ],
            options={
                'verbose_name': '编号序列',
                'verbose_name_plural': '编号序列',
                'db_table': 'commons_sequence',
                'unique_together': {('prefix', 'year', 'month', 'day')},
            },
        ),
        migrations.CreateModel(
            name='StatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('from_status', models.CharField(max_length=30, verbose_name='原状态')),
                ('to_status', models.CharField(max_length=30, verbose_name='新状态')),
                ('action', models.CharField(max_length=30, verbose_name='操作')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('operator',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL,
                                   verbose_name='操作人')),
            ],
            options={
                'verbose_name': '状态变更日志',
                'verbose_name_plural': '状态变更日志',
                'db_table': 'commons_status_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UOMConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio', models.DecimalField(decimal_places=6, max_digits=12, verbose_name='换算比例')),
                ('from_uom',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_conversions',
                                   to='commons.uom', verbose_name='原单位')),
            ],
            options={
                'verbose_name': '单位换算',
                'verbose_name_plural': '单位换算',
                'db_table': 'commons_uom_conversion',
            },
        ),
    ]
