# Generated by Django 5.2.15 on 2026-07-04 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('commons', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uomconversion',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uom_conversions',
                                    to='inventory.product', verbose_name='商品'),
        ),
        migrations.AddField(
            model_name='uomconversion',
            name='to_uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_conversions',
                                    to='commons.uom', verbose_name='目标单位'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['type'], name='commons_par_type_b23cdf_idx'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['code'], name='commons_par_code_979462_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['employee_id'], name='users_user_employe_e638d5_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone'], name='users_user_phone_9474e8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='uomconversion',
            unique_together={('product', 'from_uom', 'to_uom')},
        ),
    ]
