# Generated by Django 5.2.15 on 2026-07-04 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('commons', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=50, unique=True, verbose_name='销售单号')),
                ('order_date', models.DateField(verbose_name='订单日期')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '待审核'), ('confirmed', '已审核'),
                                                     ('partially_delivered', '部分出库'), ('done', '已完成'),
                                                     ('cancelled', '已取消')], default='draft', max_length=20,
                                            verbose_name='状态')),
                ('total_amount',
                 models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='总金额')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                 related_name='sales_orders_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(limit_choices_to={'type__in': ['customer', 'both']},
                                               on_delete=django.db.models.deletion.PROTECT, to='commons.partner',
                                               verbose_name='客户')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                 related_name='sales_orders_updated', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse',
                                                verbose_name='出货仓库')),
            ],
            options={
                'verbose_name': '销售订单',
                'verbose_name_plural': '销售订单',
                'db_table': 'sales_salesorder',
            },
        ),
        migrations.CreateModel(
            name='SalesOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.IntegerField(verbose_name='行号')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='数量')),
                ('delivered_qty',
                 models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='已出库数量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='单价')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='税率(%)')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='小计')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines',
                                            to='sales.salesorder', verbose_name='销售订单')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product',
                                              verbose_name='商品')),
                ('uom',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commons.uom', verbose_name='单位')),
            ],
            options={
                'verbose_name': '销售订单行',
                'verbose_name_plural': '销售订单行',
                'db_table': 'sales_salesorderline',
            },
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['order_no'], name='sales_sales_order_n_5a1c26_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['status'], name='sales_sales_status_480214_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['customer'], name='sales_sales_custome_b24b56_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='salesorderline',
            unique_together={('order', 'line_no')},
        ),
    ]
